### ISSUE TITLE
Define MODES of Operation

### ISSUE THREAD

**Issue by joecaraccio** [Team138Entropy/Entropy2020#29]
All hands on deck issue here! We need to think a little bit about how the Robot actually operates during TELEOP, and various modes of what the operator would want to control. I drew up a initial draft for discussion 

https://imgur.com/a/lnBKI5R

**Comment by joecaraccio** [comment]
Correction to that table.. I don't think we will have elevation control, but adjusting exit velocities will be the same thing

**Comment by Team138Entropy** [comment]
Joe, do you have this in a document we can all collaborate on? Maybe we could add this to the Wiki as a Markdown table until we have the ConOps document ready.
Comments:
- How do you envision enabling  /disabling auto modes? The controllers will probably be a little cluttered with the manual controls, so I would suggest virtual switches on Shuffleboard
- Should **Manual Acquire** be enabled by default since **Harvest Mode (Auto Acquire)** is disabled by default?
- In seasons past we have assigned operational items like intake (acquisition) to the operator. On your chart you have the entire **Manual Acquire** assigned to the Driver. I suggest splitting this one between the Driver and Operator
- For the **Auto** operations I suggest denoting **Robot** as the _Controller_
- We could probably add another column that lists proposed Controls

**Comment by joecaraccio** [comment]
https://drive.google.com/file/d/0B_Tq6mYckE93aEdTbWUweVhGVkoxajRWSzYtTktVWlB4Skc4/view?usp=sharing

**Comment by joecaraccio** [comment]
Definetly not virtual switches. Triggers on operator and driver controllers

**Comment by Team138Entropy** [comment]
Regarding virtual switches on the Shuffleboard:
- We're going to run out of buttons because they'll likely be assigned to manual operations
- Switching from Auto to Manual or vice versa _shouldn't_ be something that the operator does very often. If they do that inadvertently, the Robot will start behaving in an unexpected manner to the operator, so we'll need to assign buttons that are out of the way.

**Comment by joecaraccio** [comment]
Long presses or double presses would solve that. Latency of the driver or operator having to find the laptop mouse and click would be brutal mid match
